language: python
python:
  - "3.5"
dist: trusty
sudo: required
before_install:
  - travis_retry sudo add-apt-repository -y ppa:ethereum/ethereum
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install -y solc
cache:
  pip: true
env:
  matrix:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=flake8
cache: pip
install:
  - travis_retry pip install setuptools --upgrade
  - travis_retry pip install tox
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
