language: python
python:
  - "3.5"
dist: trusty
sudo: required
env:
  matrix:
    - TOX_ENV=py27 SOLC_BINARY="$TRAVIS_BUILD_DIR/solc-versions/solc-0.3.6/solc"
    - TOX_ENV=py34 SOLC_BINARY="$TRAVIS_BUILD_DIR/solc-versions/solc-0.3.6/solc"
    - TOX_ENV=py35 SOLC_BINARY="$TRAVIS_BUILD_DIR/solc-versions/solc-0.3.6/solc"
    - TOX_ENV=py27 SOLC_BINARY="$TRAVIS_BUILD_DIR/solc-versions/solc-0.4.1/solc"
    - TOX_ENV=py34 SOLC_BINARY="$TRAVIS_BUILD_DIR/solc-versions/solc-0.4.1/solc"
    - TOX_ENV=py35 SOLC_BINARY="$TRAVIS_BUILD_DIR/solc-versions/solc-0.4.1/solc"
    - TOX_ENV=py27 SOLC_BINARY="$TRAVIS_BUILD_DIR/solc-versions/solc-0.4.2/solc"
    - TOX_ENV=py34 SOLC_BINARY="$TRAVIS_BUILD_DIR/solc-versions/solc-0.4.2/solc"
    - TOX_ENV=py35 SOLC_BINARY="$TRAVIS_BUILD_DIR/solc-versions/solc-0.4.2/solc"
    - TOX_ENV=flake8
cache:
  - pip: true
  - directories:
    - $TRAVIS_BUILD_DIR/solc-versions/solc-0.3.6
    - $TRAVIS_BUILD_DIR/solc-versions/solidity-0.3.6/build
    - $TRAVIS_BUILD_DIR/solc-versions/solc-0.4.1
    - $TRAVIS_BUILD_DIR/solc-versions/solidity-0.4.1/build
    - $TRAVIS_BUILD_DIR/solc-versions/solc-0.4.2
    - $TRAVIS_BUILD_DIR/solc-versions/solidity-0.4.2/build
install:
  - ./bin/install_solc-0.3.6.sh
  - ./bin/install_solc-0.4.1.sh
  - ./bin/install_solc-0.4.2.sh
  - travis_retry pip install setuptools --upgrade
  - travis_retry pip install tox
before_script:
  - ./solc-versions/solc-0.3.6/solc --version
  - ./solc-versions/solc-0.4.1/solc --version
  - ./solc-versions/solc-0.4.2/solc --version
script:
  - env
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
