language: python
python:
  - "3.5"
dist: trusty
sudo: required
cache:
  pip: true
env:
  global:
    - SOLC_BINARY="$TRAVIS_BUILD_DIR/solc-versions/solc-0.3.6/solc"
  matrix:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=flake8
cache:
  - pip: true
  - directories:
    - solc-versions/solc-0.3.6
    - solc-versions/solidity-0.3.6/build
install:
  - ./bin/install_solc.sh
  - travis_retry pip install setuptools --upgrade
  - travis_retry pip install tox
before_script:
  - ls -lah $TRAVIS_BUILD_DIR/solc-versions/solc-0.3.6/
  - ./solc-versions/solc-0.3.6/solc --version
script:
  - env
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
